apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-ai
      containers:
        - name: qdrant
          image: docker.m.daocloud.io/qdrant/qdrant:v1.12.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6333
            - name: grpc
              containerPort: 6334
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      volumes:
        - name: qdrant-storage
          hostPath:
            path: /root/aiops-agent/qdrant-storage
            type: DirectoryOrCreate