apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: { requests: { storage: 2Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector: { matchLabels: { app: prometheus } }
  template:
    metadata: { labels: { app: prometheus } }
    spec:
      serviceAccountName: prometheus
      nodeSelector: { kubernetes.io/hostname: worker-monitor }
      containers:
      - name: prometheus
        image: docker.m.daocloud.io/prom/prometheus:v2.51.2
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-admin-api"
        ports: [{ containerPort: 9090 }]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data-volume
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap: { name: prometheus-config }
      - name: data-volume
        persistentVolumeClaim: { claimName: prometheus-pvc }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector: { matchLabels: { app: grafana } }
  template:
    metadata: { labels: { app: grafana } }
    spec:
      nodeSelector: { kubernetes.io/hostname: worker-monitor }
      containers:
      - name: grafana
        image: docker.m.daocloud.io/grafana/grafana:10.4.1
        ports: [{ containerPort: 3000 }]
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/grafana
      volumes:
      - name: data-volume
        persistentVolumeClaim: { claimName: grafana-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32000
  selector:
    app: grafana
